### ISSUE TITLE
Remove the import 

### ISSUE THREAD

**Issue by death-angel-141** [CharmingMother/kurusaki_voice#15]
While deploying to heroku there is a problem of an unused import,ie., pymongo,which is needed to be removed for successful deploy. 
![Capture](https://user-images.githubusercontent.com/61632737/87929072-7b940680-caa3-11ea-8da5-84bcd7f31cee.PNG)

**Comment by CharmingDays** [comment]
I imported pymongo because there are some commands that use it but has been commented out for the public use. I will comment out the import and leave a note about it. Thank you
