### ISSUE TITLE
runtime.txt

### ISSUE THREAD

**Issue by whitestride** [CharmingMother/kurusaki_voice#30]
-----> Python app detected
-----> Using Python version specified in runtime.txt
 !     Requested runtime (python-3.8.2) is not available for this stack (heroku-20).
 !     Aborting.  More info: https://devcenter.heroku.com/articles/python-support
 !     Push rejected, failed to compile Python app.
 !     Push failed

changing the python runtime to 3.9 or newer seems to fix this issue

**Comment by CharmingDays** [comment]
Yes, changing it to higher version like you said should have fixed it.
